#############################################################
#
# 内置tomcat配置
#
#############################################################
server:
  port: 8088                  # web访问端口 约定为:8088
  tomcat:
    uri-encoding: utf-8
  max-http-header-size: 80KB



#############################################################
#
# 配置数据源信息
#
#############################################################
spring:
  profiles:
    active: prod # 激活环境
  datasource:                                   # 数据源相关配置
    type: com.zaxxer.hikari.HikariDataSource    # 数据源类型: HikariCP
    driver-class-name: com.mysql.jdbc.Driver    # mysql驱动
#    url: jdbc:mysql://localhost:3306/mall-dev?characterEncoding=UTF-8&useSSL=false&useUnicode=true&serverTimezone=UTC
#    username: root
#    password: root
    hikari:
      connection-timeout: 30000 # 等待连接池分配的最大时长(毫秒),超过这个时长还没可用的连接则发生SQLException, 默认: 30秒
      minimum-idle: 5           # 最小连接数
      maximum-pool-size: 20     # 最大连接数
      auto-commit: true         # 自动提交
      idle-timeout:  600000     # 连接超时的最大时长(毫秒), 超时则被释放(retired),默认:10分钟
      pool-name: DateSourceHikariCP # 连接池名字
      max-lifetime: 1800000     # 连接的生命时长(毫秒), 超时而且没被使用则被释放(retired), 默认30分钟 1800000ms
      connection-test-query: SELECT 1



#############################################################
#
# mybatis 配置
#
#############################################################
mybatis:
  type-aliases-package: com.icoding.pojo    # 所有POJO类所在包路径
  mapper-locations: classpath:mapper/*.xml  # mapper映射文件

#############################################################
#
# mybatis mapper 配置
#
#############################################################
# 通用mapper配置
mapper:
  mappers: com.icoding.my.mapper.MyMapper
  not-empty: false  # 在进行数据库操作的时候，判断表达式 username != null, 在sql后追加 username != ''
  identity: MYSQL
